### ISSUE TITLE
test_keyspace doesn't exist error

### ISSUE THREAD

**Issue by kant111** [tacoo/cassandra-antlr-sample#1]
I tried the example from this Repo I get the following error

```
Exception in thread "main" org.apache.cassandra.exceptions.ConfigurationException: Keyspace test_keyspace doesn't exist
	at org.apache.cassandra.cql3.statements.CreateTableStatement$RawStatement.prepare(CreateTableStatement.java:200)
	at com.hello.world.Test.main(Test.java:23)
```
Below is the code

```
package com.hello.world;

import org.antlr.runtime.ANTLRStringStream;
import org.antlr.runtime.CommonTokenStream;
import org.apache.cassandra.cql3.CqlLexer;
import org.apache.cassandra.cql3.CqlParser;
import org.apache.cassandra.cql3.statements.CreateTableStatement;
import org.apache.cassandra.cql3.statements.ParsedStatement;

public class Test {

    public static void main(String[] args) throws Exception {
        String stmt = "create table if not exists test_keyspace.my_table (field1 text, field2 int, field3 set<ascii>, field4 map<ascii, text>, primary key (field1) );";
        ANTLRStringStream stringStream = new ANTLRStringStream(stmt);
        CqlLexer cqlLexer = new CqlLexer(stringStream);
        CommonTokenStream token = new CommonTokenStream(cqlLexer);
        CqlParser parser = new CqlParser(token);
        ParsedStatement query = parser.query();
        if (query.getClass().getDeclaringClass() == CreateTableStatement.class) {
            CreateTableStatement.RawStatement cts = (CreateTableStatement.RawStatement) query;
            System.out.println(cts.keyspace());
            System.out.println(cts.columnFamily());
            ParsedStatement.Prepared prepared = cts.prepare();
            CreateTableStatement cts2 = (CreateTableStatement) prepared.statement;
            cts2.getCFMetaData()
                    .getColumnMetadata()
                    .values()
                    .stream()
                    .forEach(cd -> System.out.println(cd));
        }
    }
}
```

**Comment by tacoo** [comment]
Thank you for the report. It looks like this is no longer valid.
